apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-news-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-news
  template:
    metadata:
      name: portal-news
      labels:
        app: portal-news
    spec:
      containers:
        - name: portal-news-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-news-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 10m
